os: windows
sudo: false
language: go
go:
  # - '1.0'
  # - '1.1'
  # - '1.2'
  # - '1.3'
  # - '1.4'
  # - '1.5'
  # - '1.6'
  # - '1.7'
  # - '1.8'
  # - '1.9'
  - '1.10'
  - '1.11'
  # - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/akavel/rsrc/binutil
  - go get github.com/akavel/rsrc/coff
  - go get github.com/akavel/rsrc/ico
script:
  # Install binary.
  - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
  # Test building.
  - bash $GOPATH/src/github.com/josephspurrier/goversioninfo/testdata/bash/build.sh
  # Run tests and send coverage info.
  - cd $GOPATH/src/github.com/josephspurrier/goversioninfo && $GOPATH/bin/goveralls -service=travis-ci