os: windows
sudo: false
language: go
go:
  - "1.12"
  - "1.13"
  - "1.14"
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - pwd
  # Install binary.
  #- go install github.com/$TRAVIS_REPO_SLUG/cmd/goversioninfo
  # Test building 32 and 64 on Windows.
  - make test-integration
  # Run Go tests and send coverage info.
  - cd $TRAVIS_BUILD_DIR
  - $GOPATH/bin/goveralls -service=travis-ci
